# Generated by Django 4.0.3 on 2022-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='project_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='todo.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail_url',
            field=models.URLField(default=''),
        ),
    ]
