# Generated by Django 4.0.3 on 2022-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
