# Generated by Django 4.0.3 on 2022-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_tags_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
