# Generated by Django 4.0.3 on 2022-04-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_project_url_alter_todo_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
