# Generated by Django 4.0.3 on 2022-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_tags_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
