name: Front End Unit Tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target
        id: target-branch
        run: |
         echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.target-branch.outputs.name }}

      - name: Run Unit Tests
        run: |
          cd frontend
          yarn
          yarn test:ci
